name: Update Homebrew Tap
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (without v prefix)'
        required: true
        type: string
jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout amux repository
        uses: actions/checkout@v4
      - name: Get release version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="v${{ inputs.version }}"
          fi
          # Remove 'v' prefix if present
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Run update script
        run: |
          cd scripts/homebrew-tap
          ./update-formula.sh "${{ steps.version.outputs.version }}"
      - name: Trigger homebrew-amux update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          repository: choplin/homebrew-amux
          event-type: update-formula
          client-payload: |-
            {
              "version": "${{ steps.version.outputs.version }}",
              "formula_url": "https://raw.githubusercontent.com/choplin/amux/${{ github.sha }}/scripts/homebrew-tap/amux.rb"
            }
